#!/bin/bash
echo "=========================================="
echo "   KI - Quick Check"
echo "=========================================="
echo ""
echo "[1] Python:"
python3 --version && echo "✓ OK" || echo "✗ FAIL"
echo ""
echo "[2] Virtual Environment:"
[ -f "/mnt/c/Users/Gohanckz/Desktop/IA-Proyect/venv/bin/activate" ] && echo "✓ Found" || echo "✗ Not found"
echo ""
echo "[3] Packages:"
source /mnt/c/Users/Gohanckz/Desktop/IA-Proyect/venv/bin/activate
python3 -c "import gradio" 2>/dev/null && echo "✓ gradio" || echo "✗ gradio"
python3 -c "import ollama" 2>/dev/null && echo "✓ ollama" || echo "✗ ollama"
python3 -c "import pydantic_settings" 2>/dev/null && echo "✓ pydantic-settings" || echo "✗ pydantic-settings"
python3 -c "import PyPDF2" 2>/dev/null && echo "✓ PyPDF2" || echo "✗ PyPDF2"
echo ""
echo "=========================================="
echo "To start: ./start.sh"
echo "=========================================="
